title: PowerShell for SysAdmins
description: Learn how to automate common system administration tasks with PowerShell scripts and modules. Improve your productivity and efficiency as a system administrator.
theme: just-the-docs

url: https://theepicnik.github.io/powershellforsysadmins

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

enable_copy_code_button: true

logo: "/assets/images/powershellforsysadmins.png"
favicon_ico: "/assets/images/favicon.ico"